const madLibsKeys = function() {
  const zoo = [
    "pluralNoun1",
    "pluralNoun2",
    "adj1",
    "typeOfLiquid",
    "pluralAnimal",
    "adj2",
    "funnyNoise1",
    "funnyNoise2",
    "adj3",
    "pluralNoun2",
    "animal1",
    "animal2",
    "partOfBody",
    "pluralNoun3",
    "adj4"
  ];
  const amusementPark = [
    "noun1",
    "articleOfClothing",
    "adj1",
    "adj2",
    "noun2",
    "pluralNoun1",
    "noun3",
    "adj3",
    "typeOfFood",
    "typeOfLiquid",
    "partOfBody",
    "pluralNoun2",
    "pluralNoun3",
    "animal",
    "noun4"
  ];
  const baseballGame = [
    "color",
    "pluralNoun",
    "adj1",
    "celebrity1",
    "adj2",
    "noun1",
    "number1",
    "number2",
    "noun2",
    "adj3",
    "celebrity2",
    "celebrity3",
    "adj4",
    "noun3",
    "celebrity4",
    "adj5"
  ];
  const dog = [
    "noun1",
    "adj1",
    "adj2",
    "noun2",
    "noun3",
    "adverb",
    "noun4",
    "noun5",
    "color",
    "adj3",
    "adj4",
    "number",
    "adj5",
    "pluralNoun1",
    "adj6",
    "noun6"
  ];
  const invention = [
    "noun1",
    "adj1",
    "famousPerson1",
    "famousPerson2",
    "noun2",
    "pluralNoun1",
    "exclamation",
    "noun3",
    "adj2",
    "pluralNoun2",
    "noun4",
    "pluralTypeOfFood",
    "typeOfLiquid",
    "noun5",
    "adj3",
    "number",
    "adverb"
  ];
  const lateExcuses = [
    "adj1",
    "personYouKnow1",
    "adj2",
    "partOfBody",
    "noun1",
    "noun2",
    "number",
    "pluralNoun1",
    "typeOfLiquid",
    "adverb",
    "personYouKnow2",
    "adj3",
    "adj4",
    "personYouKnow2",
    "adj5",
    "adj6",
    "adj7",
    "pluralNoun2",
    "noun3",
    "pluralNoun3",
    "verb",
    "pluralNoun4"
  ];
  const martialArts = [
    "pluralNoun1",
    "adj1",
    "personYouKnow",
    "adj2",
    "noun1",
    "adj3",
    "pluralNoun2",
    "animal",
    "verb",
    "noun2",
    "noun3",
    "partOfBody",
    "noun4",
    "noun5",
    "pluralPartOfBody"
  ];
  return {
    zoo,
    amusementPark,
    baseballGame,
    dog,
    invention,
    lateExcuses,
    martialArts
  };
}

module.exports = madLibsKeys();
